-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: May 28, 2016 at 02:23 PM
-- Server version: 5.7.9
-- PHP Version: 5.6.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movie_theatre`
--

-- --------------------------------------------------------

--
-- Table structure for table `movietomatoes`
--

DROP TABLE IF EXISTS `movietomatoes`;
CREATE TABLE IF NOT EXISTS `movietomatoes` (
  `mtImdbID` varchar(11) NOT NULL,
  `mtMovieTitle` varchar(50) NOT NULL,
  `mtAllCritics` varchar(500) DEFAULT NULL,
  `mtTopCritics` varchar(500) DEFAULT NULL,
  `mtAudienceScore` varchar(100) DEFAULT NULL,
  `mtMovieDescription` varchar(3000) DEFAULT NULL,
  `mtGenre` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`mtImdbID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `movietomatoes`
--

INSERT INTO `movietomatoes` (`mtImdbID`, `mtMovieTitle`, `mtAllCritics`, `mtTopCritics`, `mtAudienceScore`, `mtMovieDescription`, `mtGenre`) VALUES
('tt1608290', 'Zoolander 2', '{"freshness":"rotten","tomatometer":24,"averageRating":"4.5/10","reviewCount":182,"freshCount":43,"rottenCount":139,"criticsConsensus":"Zoolander No. 2 has more celebrity cameos than laughs -- and its meager handful of memorable gags outnumbers the few worthwhile ideas discernible in its scattershot rehash of a script."}', '{"freshness":"rotten","tomatometer":17,"averageRating":"4.8/10","reviewCount":41,"freshCount":7,"rottenCount":34,"criticsConsensus":"Zoolander No. 2 has more celebrity cameos than laughs -- and its meager handful of memorable gags outnumbers the few worthwhile ideas discernible in its scattershot rehash of a script."}', '{"tomatometer":"27","averageRating":"2.5/5","ratingCount":39039}', 'Ben Stiller returns both in front of and behind the camera for Zoolander 2, a comedy that finds the beloved model Derek Zoolander (Stiller) and his rival-turned-partner Hansel (Owen Wilson) facing a threat to their continued success.more', '["Comedy"]'),
('tt2975590', 'Batman v Superman: Dawn of Justice', '{"freshness":"rotten","tomatometer":28,"averageRating":"4.9/10","reviewCount":320,"freshCount":89,"rottenCount":231,"criticsConsensus":"Batman v Superman: Dawn of Justice smothers a potentially powerful story -- and some of America''s most iconic superheroes -- in a grim whirlwind of effects-driven action."}', '{"freshness":"rotten","tomatometer":26,"averageRating":"4.9/10","reviewCount":47,"freshCount":12,"rottenCount":35,"criticsConsensus":"Batman v Superman: Dawn of Justice smothers a potentially powerful story -- and some of America''s most iconic superheroes -- in a grim whirlwind of effects-driven action."}', '{"tomatometer":"68","averageRating":"3.7/5","ratingCount":201550}', 'Batman (Ben Affleck) and Superman (Henry Cavill) share the screen in this Warner Bros./DC Entertainment co-production penned by David S. Goyer and Chris Terrio, and directed by Zack Snyder. Amy Adams and Diane Lane return as Lois Lane and Martha Kent, respectively.more', '["Action & Adventure","Science Fiction & Fantasy"]'),
('tt2948356', 'Zootopia', '{"freshness":"rotten","tomatometer":98,"averageRating":"8.1/10","reviewCount":206,"freshCount":202,"rottenCount":4,"criticsConsensus":"The brilliantly well-rounded Zootopia offers a thoughtful, inclusive message that''s as rich and timely as its sumptuously state-of-the-art animation -- all while remaining fast and funny enough to keep younger viewers entertained."}', '{"freshness":"rotten","tomatometer":97,"averageRating":"8/10","reviewCount":39,"freshCount":38,"rottenCount":1,"criticsConsensus":"The brilliantly well-rounded Zootopia offers a thoughtful, inclusive message that''s as rich and timely as its sumptuously state-of-the-art animation -- all while remaining fast and funny enough to keep younger viewers entertained."}', '{"tomatometer":"95","averageRating":"4.5/5","ratingCount":61724}', 'The modern mammal metropolis of Zootopia is a city like no other. Comprised of habitat neighborhoods like ritzy Sahara Square and frigid Tundratown, it''s a melting pot where animals from every environment live together-a place where no matter what you are, from the biggest elephant to the smallest shrew, you can be anything. But when rookie Officer Judy Hopps (voice of Ginnifer Goodwin) arrives, she discovers that being the first bunny on a police force of big, tough animals isn''t so easy. Determined to prove herself, she jumps at the opportunity to crack a case, even if it means partnering with a fast-talking, scam-artist fox, Nick Wilde (voice of Jason Bateman), to solve the mystery. Walt Disney Animation Studios'' "Zootopia," a comedy-adventure directed by Byron Howard ("Tangled," "Bolt") and Rich Moore ("Wreck-It Ralph," "The Simpsons") and co-directed by Jared Bush ("Penn Zero: Part-Time Hero"), opens in theaters on March 4, 2016. Officer Judy Hopps (voice of Ginnifer Goodwin), the very first bunny on Zootopia''s police force, jumps at the opportunity to crack her first case-even if it means partnering with fast-talking, scam-artist fox Nick Wilde (voice of Jason Bateman) to solve the mystery.more', '["Action & Adventure","Animation","Comedy"]'),
('tt4257926', 'Miracles from Heaven', '{"freshness":"rotten","tomatometer":47,"averageRating":"5.1/10","reviewCount":75,"freshCount":35,"rottenCount":40,"criticsConsensus":"Miracles from Heaven makes the most out of an outstanding performance from Jennifer Garner, but it isn''t quite enough to keep this faith-based drama from preaching to the choir."}', '{"freshness":"rotten","tomatometer":52,"averageRating":"4.7/10","reviewCount":21,"freshCount":11,"rottenCount":10,"criticsConsensus":"Miracles from Heaven makes the most out of an outstanding performance from Jennifer Garner, but it isn''t quite enough to keep this faith-based drama from preaching to the choir."}', '{"tomatometer":"83","averageRating":"4.2/5","ratingCount":15166}', 'When Christy discovers her 10-year-old daughter Anna has a rare, incurable disease, she becomes a ferocious advocate for her daughter''s healing as she searches for a solution. After Anna has a freak accident, an extraordinary miracle unfolds in the wake of her dramatic rescue that leaves medical specialists mystified, her family restored and their community inspired. Based on a true story.more', '["Drama"]'),
('tt3040964', 'The Jungle Book', '{"freshness":"rotten","tomatometer":94,"averageRating":"7.8/10","reviewCount":204,"freshCount":192,"rottenCount":12,"criticsConsensus":"As lovely to behold as it is engrossing to watch, The Jungle Book is the rare remake that actually improves upon its predecessors -- all while setting a new standard for CGI."}', '{"freshness":"rotten","tomatometer":93,"averageRating":"7.9/10","reviewCount":42,"freshCount":39,"rottenCount":3,"criticsConsensus":"As lovely to behold as it is engrossing to watch, The Jungle Book is the rare remake that actually improves upon its predecessors -- all while setting a new standard for CGI."}', '{"tomatometer":"92","averageRating":"4.3/5","ratingCount":43163}', 'Rudyard Kipling''s beloved story returns to the screen in this Walt Disney Pictures production from director Jon Favreau (Elf, Iron Man). ~ Jason Buchanan, Rovimore', '["Action & Adventure","Kids & Family"]'),
('tt4701660', 'Mei ren yu (The Mermaid)', '{"freshness":"fresh","tomatometer":91,"averageRating":"7/10","reviewCount":22,"freshCount":20,"rottenCount":2,"criticsConsensus":"The Mermaid requires a willingness to embrace the strange, but backs up its wacky flights of fancy with a big-hearted fairy tale and a resonant message."}', '{"freshness":"fresh","tomatometer":89,"averageRating":"6/10","reviewCount":9,"freshCount":8,"rottenCount":1,"criticsConsensus":"The Mermaid requires a willingness to embrace the strange, but backs up its wacky flights of fancy with a big-hearted fairy tale and a resonant message."}', '{"tomatometer":"74","averageRating":"3.8/5","ratingCount":2347}', 'Xuan''s real estate project involved reclamation of the sea, threatening the livelihood of the residents who relied on the sea to make a living. Bearing family secrets, Shan was dispatched to stop Xuan. During their encounters, they fall in love with each other. Even though Xuan stopped the reclamation plan out of his love for Shan, Shan got injured in an accident and vanished into the sea.more', '["Science Fiction & Fantasy","Comedy"]'),
('tt1431045', 'Deadpool', '{"freshness":"rotten","tomatometer":83,"averageRating":"6.9/10","reviewCount":256,"freshCount":213,"rottenCount":43,"criticsConsensus":"Fast, funny, and gleefully profane, the fourth-wall-busting Deadpool subverts superhero film formula with wildly entertaining -- and decidedly non-family-friendly -- results."}', '{"freshness":"rotten","tomatometer":73,"averageRating":"6.6/10","reviewCount":40,"freshCount":29,"rottenCount":11,"criticsConsensus":"Fast, funny, and gleefully profane, the fourth-wall-busting Deadpool subverts superhero film formula with wildly entertaining -- and decidedly non-family-friendly -- results."}', '{"tomatometer":"92","averageRating":"4.4/5","ratingCount":161832}', 'Based upon Marvel Comics'' most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life. (C) Foxmore', '["Action & Adventure","Science Fiction & Fantasy","Comedy"]'),
('tt2267968', 'Kung Fu Panda 3', '{"freshness":"rotten","tomatometer":86,"averageRating":"6.8/10","reviewCount":143,"freshCount":123,"rottenCount":20,"criticsConsensus":"Kung Fu Panda 3 boasts the requisite visual splendor, but like its rotund protagonist, this sequel''s narrative is also surprisingly nimble, adding up to animated fun for the whole family."}', '{"freshness":"rotten","tomatometer":74,"averageRating":"6.4/10","reviewCount":31,"freshCount":23,"rottenCount":8,"criticsConsensus":"Kung Fu Panda 3 boasts the requisite visual splendor, but like its rotund protagonist, this sequel''s narrative is also surprisingly nimble, adding up to animated fun for the whole family."}', '{"tomatometer":"82","averageRating":"4/5","ratingCount":91629}', 'In 2016, one of the most successful animated franchises in the world returns with its biggest comedy adventure yet, KUNG FU PANDA 3. When Po''s long-lost panda father suddenly reappears, the reunited duo travels to a secret panda paradise to meet scores of hilarious new panda characters. But when the supernatural villain Kai begins to sweep across China defeating all the kung fu masters, Po must do the impossible-learn to train a village full of his fun-loving, clumsy brethren to become the ultimate band of Kung Fu Pandas! (C) Foxmore', '["Animation"]'),
('tt4824302', 'Mother''s Day', '{"freshness":"rotten","tomatometer":8,"averageRating":"2.9/10","reviewCount":87,"freshCount":7,"rottenCount":80,"criticsConsensus":"Arguably well-intended yet thoroughly misguided, Mother''s Day is the cinematic equivalent of a last-minute gift that only underscores its embarrassing lack of effort."}', '{"freshness":"rotten","tomatometer":8,"averageRating":"2.9/10","reviewCount":26,"freshCount":2,"rottenCount":24,"criticsConsensus":"Arguably well-intended yet thoroughly misguided, Mother''s Day is the cinematic equivalent of a last-minute gift that only underscores its embarrassing lack of effort."}', '{"tomatometer":"54","averageRating":"3.2/5","ratingCount":7223}', '"Mother''s Day" is the latest star studded ensemble comedy from director Garry Marshall ("Pretty Woman," "Valentine''s Day"). Bringing together Jennifer Aniston, Kate Hudson and Julia Roberts along with Jason Sudeikis, it''s a celebration of mothers everywhere. This big-hearted comedy invites us all to enjoy the laughter, tears and love as three generations come together in the week leading up to Mother''s Day.more', '["Drama","Comedy"]'),
('tt2381991', 'The Huntsman: Winter''s War', '{"freshness":"rotten","tomatometer":16,"averageRating":"4.2/10","reviewCount":171,"freshCount":28,"rottenCount":143,"criticsConsensus":"The Huntsman: Winter''s War is visually arresting and boasts a stellar cast, but neither are enough to recommend this entirely unnecessary sequel."}', '{"freshness":"rotten","tomatometer":9,"averageRating":"4/10","reviewCount":34,"freshCount":3,"rottenCount":31,"criticsConsensus":"The Huntsman: Winter''s War is visually arresting and boasts a stellar cast, but neither are enough to recommend this entirely unnecessary sequel."}', '{"tomatometer":"51","averageRating":"3.3/5","ratingCount":36976}', 'Freya the Ice Queen (Emily Blunt) brings her sister Ravenna (Charlize Theron) back to life, and the powerful evil siblings plan to conquer the Enchanted Forest. Only the Huntsman (Chris Hemsworth) and his secret lover Sara (Jessica Chastain) can stop them in this sequel continuing the inventive twist on the Snow White fable.more', '["Drama","Action & Adventure","Science Fiction & Fantasy"]'),
('tt4139124', 'Keanu', '{"freshness":"rotten","tomatometer":76,"averageRating":"6.6/10","reviewCount":106,"freshCount":81,"rottenCount":25,"criticsConsensus":"Keanu''s absurd premise and compulsively watchable starring duo add up to an agreeably fast-paced comedy that hits more than enough targets to make up for the misses."}', '{"freshness":"rotten","tomatometer":77,"averageRating":"6.7/10","reviewCount":30,"freshCount":23,"rottenCount":7,"criticsConsensus":"Keanu''s absurd premise and compulsively watchable starring duo add up to an agreeably fast-paced comedy that hits more than enough targets to make up for the misses."}', '{"tomatometer":"70","averageRating":"3.6/5","ratingCount":11613}', 'Keegan-Michael Key and Jordan Peele star in this comedy as two friends posing as drug dealers to get back a stolen cat. Peter Atencio directed.more', '["Action & Adventure","Comedy"]'),
('tt3774802', 'Pandemic', '{"freshness":"rotten","tomatometer":46,"averageRating":"4.7/10","reviewCount":13,"freshCount":6,"rottenCount":7,"criticsConsensus":"No consensus yet."}', '{"freshness":"rotten","tomatometer":46,"averageRating":"4.7/10","reviewCount":13,"freshCount":6,"rottenCount":7,"criticsConsensus":"No consensus yet."}', '{"tomatometer":"90","averageRating":"3.8/5","ratingCount":899}', 'Pandemic is set in the near future, where a virus of epic proportions has overtaken the planet. There are more infected than uninfected, and humanity is losing its grip on survival. Its only hope is finding a cure and keeping the infected contained. Lauren (Rachel Nichols) is a doctor, who, after the fall of New York, comes to Los Angeles to lead a team to hunt for and rescue uninfected survivors.more', '["Action & Adventure","Science Fiction & Fantasy"]'),
('tt3498820', 'Captain America: Civil War', '{"freshness":"rotten","tomatometer":90,"averageRating":"7.6/10","reviewCount":307,"freshCount":275,"rottenCount":32,"criticsConsensus":"Captain America: Civil War begins the next wave of Marvel movies with an action-packed superhero blockbuster boasting a decidedly non-cartoonish plot and the courage to explore thought-provoking themes."}', '{"freshness":"rotten","tomatometer":88,"averageRating":"7.6/10","reviewCount":50,"freshCount":44,"rottenCount":6,"criticsConsensus":"Captain America: Civil War begins the next wave of Marvel movies with an action-packed superhero blockbuster boasting a decidedly non-cartoonish plot and the courage to explore thought-provoking themes."}', '{"tomatometer":"91","averageRating":"4.4/5","ratingCount":140350}', 'Marvel''s "Captain America: Civil War" finds Steve Rogers leading the newly formed team of Avengers in their continued efforts to safeguard humanity. But after another incident involving the Avengers results in collateral damage, political pressure mounts to install a system of accountability, headed by a governing body to oversee and direct the team. The new status quo fractures the Avengers, resulting in two camps-one led by Steve Rogers and his desire for the Avengers to remain free to defend humanity without government interference, and the other following Tony Stark''s surprising decision to support government oversight and accountability.more', '["Action & Adventure","Science Fiction & Fantasy"]');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
